name: Deploy Static Website to Azure Web App - Photo-Gallery

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_592C286752954DCFAAC171E9F53D2D8F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B3F1554FF49B49E58AFF05E42A2617E8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1023A2B94BDA4A289111BE7C8163297A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: Photo-Gallery
          slot-name: Production
          package: .
